# Generated by Django 4.0.2 on 2022-07-10 20:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000)),
                ('free', models.BooleanField()),
                ('basic', models.BooleanField()),
                ('standard', models.BooleanField()),
                ('plus', models.BooleanField()),
                ('premium', models.BooleanField()),
                ('time_when_registered', models.IntegerField()),
                ('day_when_registered', models.IntegerField()),
                ('month_when_registered', models.IntegerField()),
                ('year_when_registered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='daily_ads_clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=3000)),
                ('daily_display_clicks', models.IntegerField()),
                ('daily_feed_clicks', models.IntegerField()),
                ('daily_article_clicks', models.IntegerField()),
                ('daily_daimond_clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='display_article_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='Display article ads')),
                ('budget', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('clicked', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='display_daimond_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='Daimond article ads')),
                ('budget', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('clicked', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='display_feed_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='Display feed ads')),
                ('budget', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('clicked', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='display_square_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=3000)),
                ('image', models.ImageField(upload_to='Display Square ads')),
                ('budget', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('clicked', models.IntegerField()),
                ('remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('ads_clicks_earnings', models.FloatField()),
                ('user', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='email_verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000)),
                ('token', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='investment_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('user', models.CharField(max_length=1334)),
            ],
        ),
        migrations.CreateModel(
            name='investment_plan_activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=220)),
                ('plan_name', models.CharField(max_length=220)),
                ('date_of_joining', models.CharField(max_length=1500)),
                ('when_expire', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='investment_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='investment plans images')),
                ('title', models.CharField(max_length=4000)),
                ('duration', models.CharField(max_length=4000)),
                ('amount_after_profit', models.IntegerField()),
                ('invest_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_posted', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=500)),
                ('date_time_when_posted', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('job_price_per', models.FloatField()),
                ('overall_price', models.IntegerField()),
                ('total_conversions', models.IntegerField()),
                ('done_conversions', models.IntegerField()),
                ('proof1', models.CharField(max_length=5000)),
                ('proof1_type', models.CharField(max_length=200)),
                ('proof2', models.CharField(max_length=5000)),
                ('proof2_type', models.CharField(max_length=200)),
                ('proof3', models.CharField(max_length=5000)),
                ('proof3_type', models.CharField(max_length=200)),
                ('proof4', models.CharField(max_length=5000)),
                ('proof4_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='jobs_proofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof1', models.CharField(max_length=10000)),
                ('proof2', models.CharField(max_length=10000)),
                ('proof3', models.ImageField(upload_to='jobs proofs')),
                ('proof4', models.ImageField(upload_to='jobs proofs')),
                ('job_id', models.CharField(max_length=4000)),
                ('posted_by', models.CharField(max_length=3000)),
                ('user_submitted_job', models.CharField(max_length=3000)),
                ('title', models.CharField(max_length=3000)),
                ('job_earning', models.FloatField()),
                ('status', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='logo_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2000)),
                ('sells', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='Logos for sell')),
                ('template_file', models.FileField(upload_to='Logos for sell')),
                ('template_type', models.CharField(max_length=20000)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30000)),
                ('url', models.CharField(max_length=2000)),
                ('bell_digit', models.IntegerField()),
                ('to_user', models.CharField(max_length=3000)),
                ('date', models.CharField(max_length=3000)),
                ('unseen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000)),
                ('payment_account', models.CharField(max_length=2000)),
                ('payment_proof', models.ImageField(upload_to='Payment history')),
                ('applied_for', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='pictures_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2000)),
                ('sells', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='Photos for sell')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='referals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter', models.CharField(max_length=2000)),
                ('referal_user', models.CharField(max_length=2000)),
                ('reward', models.CharField(max_length=2000)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='request_for_investment_plan_activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('plan_name', models.CharField(max_length=2000)),
                ('payment_account', models.CharField(max_length=2000)),
                ('payment_proof', models.FileField(upload_to='Payments proofs for Investment plans')),
            ],
        ),
        migrations.CreateModel(
            name='thumbnails_selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2000)),
                ('sells', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='Thumbnails for sell')),
                ('title', models.TextField()),
                ('template_file', models.FileField(upload_to='Logos for sell')),
                ('template_type', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='user_clicks_ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_ads_clicks', models.IntegerField()),
                ('feed_ads_clicks', models.IntegerField()),
                ('article_ads_clicks', models.IntegerField()),
                ('daimond_ads_clicks', models.IntegerField()),
                ('user', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('second_name', models.CharField(max_length=130)),
                ('user', models.CharField(default='No info', max_length=124)),
                ('email_adress', models.CharField(default='No Email', max_length=300)),
                ('country', models.CharField(max_length=130)),
                ('profile_image', models.ImageField(upload_to='profile pics')),
            ],
        ),
        migrations.CreateModel(
            name='withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('amount_to_withdraw', models.FloatField()),
                ('payment_method', models.CharField(max_length=3000)),
                ('payment_account_info', models.CharField(max_length=3000)),
                ('status', models.BooleanField(default=False)),
                ('paid_on', models.CharField(max_length=500)),
            ],
        ),
    ]
