# Generated by Django 4.0.2 on 2022-07-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='investment_plans',
        ),
        migrations.DeleteModel(
            name='logo_selling',
        ),
        migrations.DeleteModel(
            name='pictures_selling',
        ),
        migrations.DeleteModel(
            name='thumbnails_selling',
        ),
    ]
