# Generated by Django 4.0.2 on 2022-07-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_investment_plans_delete_logo_selling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
