# Generated by Django 4.0.2 on 2022-07-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_account_type_delete_daily_ads_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='ads_clicks_earnings',
        ),
    ]
