# Generated by Django 4.0.2 on 2022-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_categories_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='sub_category',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
