# Generated by Django 4.0.2 on 2022-07-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobs_category_jobs_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='posted_from',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
