# Generated by Django 4.0.2 on 2022-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobs_posted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='country_code',
            field=models.CharField(default='', max_length=1200),
            preserve_default=False,
        ),
    ]
