# Generated by Django 4.0.2 on 2022-07-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_details_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='allowed_countries',
            field=models.CharField(default='', max_length=50000),
            preserve_default=False,
        ),
    ]
