# Generated by Django 4.0.2 on 2022-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_jobs_allowed_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='featured_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
