# Generated by Django 4.0.2 on 2022-07-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_jobs_featured_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='featured_price',
            field=models.IntegerField(default=0),
        ),
    ]
