# Generated by Django 4.0.2 on 2022-07-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_jobs_featured_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='featured_price',
            new_name='feature_price',
        ),
    ]
