# Generated by Django 4.0.2 on 2022-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_featured_price_jobs_feature_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='overall_price',
            field=models.FloatField(),
        ),
    ]
