# Generated by Django 4.0.2 on 2022-07-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_jobs_overall_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='spent_on_jobs',
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
    ]
