# Generated by Django 4.0.2 on 2022-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_jobs_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='country',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
