# Generated by Django 4.0.2 on 2022-07-27 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_jobs_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
