# Generated by Django 4.0.2 on 2022-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_jobs_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='fake_proof_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=2000)),
                ('proof_id', models.CharField(max_length=2000)),
                ('job_owner', models.CharField(max_length=2200)),
                ('user_submitted_job', models.CharField(max_length=2200)),
                ('reason', models.TextField()),
            ],
        ),
    ]
