# Generated by Django 4.0.2 on 2022-08-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_fake_proof_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_history',
            old_name='applied_for',
            new_name='TID',
        ),
    ]
