# Generated by Django 4.0.2 on 2022-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_applied_for_payment_history_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='deposit',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
