# Generated by Django 4.0.2 on 2022-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_jobs_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
