# Generated by Django 4.0.2 on 2022-09-18 17:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_chat_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=5000)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
