# Generated by Django 4.0.2 on 2022-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='2.png', upload_to='Articles Feature Images'),
            preserve_default=False,
        ),
    ]
