# Generated by Django 4.2.7 on 2024-02-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_question_option1_question_option2_question_option3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_image',
            field=models.ImageField(default='/test_images/default.png', upload_to='test_images/'),
        ),
    ]
