# Generated by Django 4.2.7 on 2024-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_test_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_option',
            field=models.CharField(default='A', max_length=300),
            preserve_default=False,
        ),
    ]
